DROP TABLE RANDOMNUMBER;

CREATE TABLE RANDOMNUMBER (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
APP_NUMBER1 NUMBER(10, 0) DEFAULT NULL,
APP_NUMBER2 NUMBER(10, 0) DEFAULT NULL,
APP_NUMBER3 NUMBER(10, 0) DEFAULT NULL,
SWAPS NUMBER(10, 0) DEFAULT NULL,
PRIMARY KEY (ID));

DROP SEQUENCE RANDONMUMBER_ID_SEQ;

CREATE SEQUENCE RANDONMUMBER_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 100
  CACHE 100;  